@echo off
setlocal enabledelayedexpansion

echo ============================================
echo  TrendsPulse.Platform - Full Local Analysis
echo ============================================

REM -----------------------------------------------
REM STEP 0: Check Vulnerable NuGet Packages
REM -----------------------------------------------
echo.
echo [0/5] Checking for vulnerable NuGet packages...
echo -----------------------------------------------

REM Get current date and time for report
for /f "tokens=1-3 delims=/ " %%a in ('date /t') do set REPORT_DATE=%%a/%%b/%%c
for /f "tokens=1-2 delims=: " %%a in ('time /t') do set REPORT_TIME=%%a:%%b

REM Run vulnerability check and save raw output
dotnet list package --vulnerable --include-transitive > vulnerability-raw.txt 2>&1
type vulnerability-raw.txt

REM Check if vulnerabilities found
set VULN_STATUS=No vulnerable packages found
set VULN_COLOR=#28a745
set VULN_ICON=✅
findstr /C:"has the following vulnerable packages" vulnerability-raw.txt >nul
if %ERRORLEVEL% EQU 0 (
    set VULN_STATUS=⚠️ Vulnerable packages detected!
    set VULN_COLOR=#dc3545
    set VULN_ICON=❌
)

REM -----------------------------------------------
REM Generate HTML Report
REM -----------------------------------------------
echo Generating HTML vulnerability report...

set HTML_FILE=vulnerability-report.html

(
echo ^<!DOCTYPE html^>
echo ^<html lang="en"^>
echo ^<head^>
echo   ^<meta charset="UTF-8"^>
echo   ^<meta name="viewport" content="width=device-width, initial-scale=1.0"^>
echo   ^<title^>TrendsPulse - NuGet Vulnerability Report^</title^>
echo   ^<style^>
echo     * { margin: 0; padding: 0; box-sizing: border-box; }
echo     body { font-family: 'Segoe UI', sans-serif; background: #f4f6f9; color: #333; }
echo     .header { background: #1a1a2e; color: white; padding: 30px 40px; }
echo     .header h1 { font-size: 24px; font-weight: 600; }
echo     .header p { margin-top: 6px; color: #aaa; font-size: 14px; }
echo     .container { max-width: 1000px; margin: 30px auto; padding: 0 20px; }
echo     .summary-card { background: white; border-radius: 10px; padding: 25px; margin-bottom: 25px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); border-left: 5px solid !VULN_COLOR!; }
echo     .summary-card h2 { font-size: 18px; margin-bottom: 10px; }
echo     .badge { display: inline-block; padding: 6px 16px; border-radius: 20px; font-size: 13px; font-weight: 600; background: !VULN_COLOR!; color: white; }
echo     .meta { margin-top: 15px; font-size: 13px; color: #666; }
echo     .meta span { margin-right: 20px; }
echo     .report-box { background: white; border-radius: 10px; padding: 25px; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
echo     .report-box h2 { font-size: 16px; margin-bottom: 15px; color: #444; border-bottom: 1px solid #eee; padding-bottom: 10px; }
echo     pre { background: #1e1e1e; color: #d4d4d4; padding: 20px; border-radius: 8px; font-size: 13px; line-height: 1.6; overflow-x: auto; white-space: pre-wrap; word-wrap: break-word; }
echo     .footer { text-align: center; padding: 20px; font-size: 12px; color: #999; margin-top: 20px; }
echo     .tip { background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 15px 20px; margin-bottom: 25px; font-size: 13px; }
echo     .tip strong { color: #856404; }
echo   ^</style^>
echo ^</head^>
echo ^<body^>
echo ^<div class="header"^>
echo   ^<h1^>🔐 NuGet Vulnerability Report^</h1^>
echo   ^<p^>TrendsPulse.Platform — Dependency Security Scan^</p^>
echo ^</div^>
echo ^<div class="container"^>
echo   ^<div class="summary-card"^>
echo     ^<h2^>Scan Summary^</h2^>
echo     ^<span class="badge"^>!VULN_STATUS!^</span^>
echo     ^<div class="meta"^>
echo       ^<span^>📅 Date: %REPORT_DATE%^</span^>
echo       ^<span^>🕐 Time: %REPORT_TIME%^</span^>
echo       ^<span^>📦 Project: TrendsPulse.Platform^</span^>
echo     ^</div^>
echo   ^</div^>
echo   ^<div class="tip"^>
echo     ^<strong^>💡 Tip:^</strong^> To fix vulnerable packages run:
echo     ^<code^>dotnet add package ^<PackageName^> --version ^<SafeVersion^>^</code^>
echo   ^</div^>
echo   ^<div class="report-box"^>
echo     ^<h2^>📋 Full Scan Output^</h2^>
echo     ^<pre^>
) > %HTML_FILE%

REM Append raw output safely into the pre block
for /f "delims=" %%i in (vulnerability-raw.txt) do (
    set "line=%%i"
    set "line=!line:<=&lt;!"
    set "line=!line:>=&gt;!"
    echo !line! >> %HTML_FILE%
)

(
echo     ^</pre^>
echo   ^</div^>
echo   ^<div class="footer"^>Generated by TrendsPulse SonarQube Local Analysis Script^</div^>
echo ^</div^>
echo ^</body^>
echo ^</html^>
) >> %HTML_FILE%

echo HTML report saved: %CD%\%HTML_FILE%
del vulnerability-raw.txt

REM -----------------------------------------------
REM STEP 1: Restore packages
REM -----------------------------------------------
echo.
echo [1/5] Restoring NuGet packages...
dotnet restore TrendsPulse.Platform.sln
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Restore failed!
    pause
    exit /b 1
)

REM -----------------------------------------------
REM STEP 2: Begin SonarQube Analysis
REM -----------------------------------------------
echo.
echo [2/5] Starting SonarQube analysis...
dotnet sonarscanner begin ^
  /k:"TrendsPulse.Platform" ^
  /n:"TrendsPulse Platform" ^
  /d:sonar.host.url="http://localhost:9000" ^
  /d:sonar.token="sqp_820afbaba15890098bdff1b919417448510c06dd" ^
  /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" ^
  /d:sonar.coverage.exclusions="**Tests*/**,**/Program.cs,**/Migrations/**" ^
  /d:sonar.exclusions="**/bin/**,**/obj/**,**/Migrations/**" ^
  /d:sonar.sourceEncoding="UTF-8"

if %ERRORLEVEL% NEQ 0 (
    echo ERROR: SonarQube begin step failed!
    echo Make sure SonarQube is running at http://localhost:9000
    pause
    exit /b 1
)

REM -----------------------------------------------
REM STEP 3: Build Solution
REM -----------------------------------------------
echo.
echo [3/5] Building solution...
dotnet build TrendsPulse.Platform.sln --no-incremental
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Build failed!
    pause
    exit /b 1
)

REM -----------------------------------------------
REM STEP 4: Run Tests with Code Coverage
REM -----------------------------------------------
echo.
echo [4/5] Running tests with code coverage...
dotnet test TrendsPulse.Platform.sln ^
  --no-build ^
  --logger "trx;LogFileName=test-results.trx" ^
  --collect:"XPlat Code Coverage" ^
  --results-directory ./TestResults ^
  -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

if %ERRORLEVEL% NEQ 0 (
    echo WARNING: Some tests failed or no test projects found. Continuing...
)

REM -----------------------------------------------
REM STEP 5: End SonarQube Analysis
REM -----------------------------------------------
echo.
echo [5/5] Uploading results to SonarQube...
dotnet sonarscanner end ^
  /d:sonar.token="sqp_820afbaba15890098bdff1b919417448510c06dd"

if %ERRORLEVEL% NEQ 0 (
    echo ERROR: SonarQube end step failed!
    pause
    exit /b 1
)

REM -----------------------------------------------
REM DONE — Auto open HTML report in browser
REM -----------------------------------------------
echo.
echo ============================================
echo  SCAN COMPLETE!
echo ============================================
echo.
echo  SonarQube Dashboard:
echo  http://localhost:9000/dashboard?id=TrendsPulse.Platform
echo.
echo  Vulnerability HTML Report:
echo  %CD%\vulnerability-report.html
echo.
echo  Test Results:
echo  %CD%\TestResults\
echo ============================================

REM Auto open the HTML report in default browser
start "" "%CD%\vulnerability-report.html"

REM Auto open SonarQube dashboard
start "" "http://localhost:9000/dashboard?id=TrendsPulse.Platform"

pause
